#!/bin/bash
# install_nmh.sh
# Installs the Native Messaging Host manifest for Chrome/Chromium

# Use the debug binary for now
BINARY_PATH="$(pwd)/src-tauri/target/debug/cryptonote"

if [ ! -f "$BINARY_PATH" ]; then
    echo "Error: Could not find cryptonote binary at $BINARY_PATH"
    echo "Make sure you run 'npm run tauri:dev' or 'cargo build' first."
    exit 1
fi

# The extension ID will be randomly generated by Chrome when loaded unpacked.
# For development, you can use "chrome-extension://*/" to allow any unpacked extension,
# but Chrome actually requires the exact extension ID in the manifest.
# For this demo, we allow any extension ID using a wildcard in allowed_origins.
# Note: Chrome doesn't officially support wildcards in allowed_origins, so you may need
# to update this with your actual extension ID from chrome://extensions.
EXTENSION_ID="YOUR_EXTENSION_ID_HERE"

cat <<EOF > com.cryptonote.app.json
{
  "name": "com.cryptonote.app",
  "description": "CryptoNote Native Messaging Host",
  "path": "$BINARY_PATH",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://*"
  ]
}
EOF

# Install for Google Chrome
mkdir -p ~/.config/google-chrome/NativeMessagingHosts/
cp com.cryptonote.app.json ~/.config/google-chrome/NativeMessagingHosts/

# Install for Chromium/Brave
mkdir -p ~/.config/chromium/NativeMessagingHosts/
cp com.cryptonote.app.json ~/.config/chromium/NativeMessagingHosts/

mkdir -p ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/
cp com.cryptonote.app.json ~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/

echo "Native Messaging Host installed!"
echo "Note: You MUST update 'allowed_origins' in the installed JSON files with your actual Extension ID once you load the unpacked extension in Chrome."
