apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: cryptonote
  annotations:
    # AWS-specific: provision an internet-facing ELB
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
